# Generated by Django 4.0 on 2024-05-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myflix_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='gross',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
