# Generated by Django 4.0 on 2024-05-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myflix_api', '0004_alter_movie_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='certificate',
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=50),
        ),
    ]
