# Generated by Django 4.0 on 2024-05-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myflix_api', '0007_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='star1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='star2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='star3',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='star4',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='myflix_api.Actor'),
        ),
    ]
